spring:
  application:
    name: notification

  datasource:
    url: jdbc:postgresql://ep-sparkling-term-a5479y8z-pooler.us-east-2.aws.neon.tech/notification?sslmode=require&channel_binding=require
    username: shorter_owner
    password: WuN1ZL0rKOhx
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
#      ddl-auto: create-drop
        ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false

server:
    port: 3030



